import { auth, db } from "../../js/firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { collection, query, orderBy, onSnapshot, doc, getDoc, updateDoc, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const $=id=>document.getElementById(id);let me=null,rows=[];const names=new Map();
const money=n=>`KES ${Number(n||0).toLocaleString("en-KE",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=v=>{if(!v)return "—";try{const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"})}catch{return "—"}};
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function toast(m,type="success"){const t=$("toast");if(!t)return;t.textContent=m;t.className=`toast show ${type}`;clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),2800)}
async function verifyFounder(u){const s=await getDoc(doc(db,"founder",u.uid));if(!s.exists()||s.data().role!=="founder"||s.data().status==="suspended"){toast("Founder authorization required","error");setTimeout(()=>location.href="../dashboard.html",900);return false}return true}
async function resolveNames(items){const ids=[...new Set(items.map(x=>x.instructorId).filter(Boolean))];await Promise.all(ids.map(async uid=>{if(names.has(uid))return;try{const s=await getDoc(doc(db,"users",uid));names.set(uid,s.exists()?(s.data().fullName||s.data().name||s.data().email||uid):uid)}catch{names.set(uid,uid)}}))}
function render(){const term=($("payoutSearch")?.value||"").trim().toLowerCase(),filter=$("payoutStatus")?.value||"all",totals={pending:[0,0],approved:[0,0],paid:[0,0],rejected:[0,0]};rows.forEach(x=>{const s=String(x.status||"pending").toLowerCase();if(totals[s]){totals[s][0]+=Number(x.amount||0);totals[s][1]++}});["pending","approved","paid","rejected"].forEach(s=>{if($(`${s}Amount`))$(`${s}Amount`).textContent=money(totals[s][0]);if($(`${s}Count`))$(`${s}Count`).textContent=`${totals[s][1]} ${s==="paid"?"payouts":"requests"}`});const list=rows.filter(x=>{const s=String(x.status||"pending").toLowerCase(),text=JSON.stringify({...x,instructorName:names.get(x.instructorId)||""}).toLowerCase();return(filter==="all"||s===filter)&&(!term||text.includes(term))}),table=$("payoutTable");if(!table)return;table.innerHTML=list.length?list.map(x=>{const s=String(x.status||"pending").toLowerCase(),name=names.get(x.instructorId)||x.instructorName||"Instructor",actions=s==="pending"?`<button class="action approve" data-a="approve" data-id="${esc(x.id)}">Approve</button><button class="action reject" data-a="reject" data-id="${esc(x.id)}">Reject</button>`:s==="approved"?`<button class="action approve" data-a="paid" data-id="${esc(x.id)}">Mark paid</button>`:`<button class="action" data-a="view" data-id="${esc(x.id)}">View</button>`;return`<tr><td><div class="person-cell"><span class="person-avatar">${esc(name.slice(0,1).toUpperCase())}</span><div><strong>${esc(name)}</strong><small>${esc(x.instructorId||"—")}</small></div></div></td><td><strong>${money(x.amount)}</strong><small class="sub-value">Net ${money(x.netAmount??Math.max(Number(x.amount||0)-Number(x.withdrawalFee||0),0))}</small></td><td><strong>${esc(x.method||"M-PESA")}</strong><small class="sub-value">${esc(x.account||"—")}</small></td><td>${date(x.createdAt||x.requestedAt)}</td><td><span class="status ${esc(s)}">${esc(s)}</span></td><td><div class="actions">${actions}</div></td></tr>`}).join(""):`<tr><td colspan="6" class="empty">No payout requests found.</td></tr>`}
async function action(id,type){if(type==="view"){const r=rows.find(x=>x.id===id);if(r)toast(`${names.get(r.instructorId)||"Instructor"} • ${money(r.amount)} • ${r.status||"pending"}`);return}const ref=doc(db,"withdrawalRequests",id),snap=await getDoc(ref);if(!snap.exists())throw Error("Payout request no longer exists.");const row=snap.data(),current=String(row.status||"pending").toLowerCase();if(type==="approve"&&current!=="pending")throw Error("Only pending requests can be approved.");if(type==="reject"&&current!=="pending")throw Error("Only pending requests can be rejected.");if(type==="paid"&&current!=="approved")throw Error("Only approved requests can be marked paid.");const status=type==="approve"?"approved":type==="reject"?"rejected":"paid",update={status,reviewedBy:me.uid,reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()};if(status==="paid"){update.paidBy=me.uid;update.paidAt=serverTimestamp()}await updateDoc(ref,update);await addDoc(collection(db,"audit_logs"),{user:me.uid,role:"founder",action:`payout_${status}`,target:id,details:`${money(row.amount)} • ${row.instructorId||"Instructor"}`,createdAt:serverTimestamp()});toast(`Payout ${status}.`)}
function watch(){const q=query(collection(db,"withdrawalRequests"),orderBy("createdAt","desc"));onSnapshot(q,async s=>{rows=s.docs.map(d=>({id:d.id,...d.data()}));await resolveNames(rows);render()},e=>{console.error(e);toast("Unable to load payout requests.","error")})}
$("payoutSearch")?.addEventListener("input",render);$("payoutStatus")?.addEventListener("change",render);$("refreshPayouts")?.addEventListener("click",render);$("payoutTable")?.addEventListener("click",e=>{const b=e.target.closest("button[data-a]");if(b)action(b.dataset.id,b.dataset.a).catch(err=>{console.error(err);toast(err.message||"Payout action failed","error")})});
onAuthStateChanged(auth,async u=>{if(!u){location.href="../../login.html";return}me=u;try{if(await verifyFounder(u))watch()}catch(e){console.error(e);toast("Security verification failed","error")}});
