const STYLE_ID="ssa-founder-palette-style";
const COMMANDS=[
 {name:"Open Command Center",hint:"Platform controls",icon:"terminal-square",url:"command-center.html",tone:"safe"},
 {name:"Security Center",hint:"Audit & protection",icon:"shield-check",url:"security.html",tone:"critical"},
 {name:"Wallets & Payouts",hint:"Finance operations",icon:"landmark",url:"wallets/wallets.html",tone:"sensitive"},
 {name:"Platform Settings",hint:"Feature controls",icon:"sliders-horizontal",url:"platform-settings.html",tone:"sensitive"},
 {name:"Student Operations",hint:"Manage learners",icon:"graduation-cap",url:"students.html",tone:"sensitive"},
 {name:"Instructor Operations",hint:"Manage teaching",icon:"users",url:"instructors.html",tone:"sensitive"},
 {name:"Broadcast Center",hint:"Academy communications",icon:"megaphone",url:"announcements.html",tone:"safe"},
 {name:"Analytics",hint:"Business intelligence",icon:"chart-column-increasing",url:"analytics.html",tone:"safe"}
];
function inject(){if(document.getElementById(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`.ssa-command-palette{position:fixed;inset:0;z-index:9999;display:none;align-items:flex-start;justify-content:center;padding:9vh 18px;background:rgba(4,14,31,.68);backdrop-filter:blur(8px)}.ssa-command-palette.open{display:flex}.ssa-palette-card{width:min(680px,100%);overflow:hidden;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:#fff;box-shadow:0 30px 90px rgba(0,0,0,.35)}.ssa-palette-head{padding:16px;border-bottom:1px solid #e8edf5}.ssa-palette-input{width:100%;box-sizing:border-box;border:0;outline:0;font:600 16px Inter,system-ui;color:#081c3a}.ssa-palette-list{max-height:58vh;overflow:auto;padding:8px}.ssa-palette-item{width:100%;display:grid;grid-template-columns:40px 1fr auto;gap:12px;align-items:center;border:0;background:#fff;text-align:left;padding:12px;border-radius:13px;cursor:pointer}.ssa-palette-item:hover,.ssa-palette-item.active{background:#f3f7ff}.ssa-palette-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;background:#eef4ff;color:#2979ff}.ssa-palette-copy strong{display:block;color:#081c3a;font-size:13px}.ssa-palette-copy span{display:block;color:#667085;font-size:11px;margin-top:3px}.ssa-palette-tone{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;color:#667085}.ssa-palette-foot{padding:10px 14px;border-top:1px solid #e8edf5;color:#98a2b3;font-size:11px}.ssa-critical-note{margin:12px 16px 0;padding:10px 12px;border-radius:11px;background:#fff8e6;color:#8a6500;font-size:11px;line-height:1.5}.ssa-founder-shortcut{position:fixed;right:18px;bottom:18px;z-index:3000;display:inline-flex;align-items:center;gap:7px;border:1px solid rgba(41,121,255,.25);border-radius:12px;background:#fff;color:#081c3a;padding:9px 12px;font:700 12px Inter,system-ui;box-shadow:0 10px 28px rgba(8,28,58,.12);cursor:pointer}@media(max-width:600px){.ssa-founder-shortcut{bottom:12px;right:12px}.ssa-palette-item{grid-template-columns:38px 1fr}.ssa-palette-tone{display:none}}`;document.head.appendChild(s)}
function start(){inject();if(document.getElementById("ssaFounderPalette"))return;const wrap=document.createElement("div");wrap.id="ssaFounderPalette";wrap.className="ssa-command-palette";wrap.innerHTML=`<div class="ssa-palette-card" role="dialog" aria-modal="true" aria-label="Founder command palette"><div class="ssa-palette-head"><input id="ssaPaletteInput" class="ssa-palette-input" autocomplete="off" placeholder="Search Founder commands…" aria-label="Search Founder commands"></div><div class="ssa-critical-note">Sensitive and critical operations open their dedicated secured workspace. They are never executed directly from this shortcut.</div><div id="ssaPaletteList" class="ssa-palette-list"></div><div class="ssa-palette-foot">Press <b>Ctrl/⌘ K</b> to open · <b>Esc</b> to close</div></div>`;document.body.appendChild(wrap);const button=document.createElement("button");button.type="button";button.className="ssa-founder-shortcut";button.innerHTML="⌘K · Founder Commands";document.body.appendChild(button);const input=wrap.querySelector("#ssaPaletteInput"),list=wrap.querySelector("#ssaPaletteList");let active=0;
 const render=()=>{const q=input.value.trim().toLowerCase();const rows=COMMANDS.filter(c=>`${c.name} ${c.hint}`.toLowerCase().includes(q));active=Math.min(active,Math.max(0,rows.length-1));list.innerHTML=rows.map((c,i)=>`<button class="ssa-palette-item ${i===active?"active":""}" data-url="${c.url}"><span class="ssa-palette-icon"><i data-lucide="${c.icon}"></i></span><span class="ssa-palette-copy"><strong>${c.name}</strong><span>${c.hint}</span></span><span class="ssa-palette-tone">${c.tone}</span></button>`).join("")||`<div style="padding:24px;text-align:center;color:#667085;font-size:13px">No matching command.</div>`;window.lucide?.createIcons()};
 const open=()=>{wrap.classList.add("open");input.value="";active=0;render();setTimeout(()=>input.focus(),20)};const close=()=>wrap.classList.remove("open");button.addEventListener("click",open);wrap.addEventListener("click",e=>{if(e.target===wrap)close();const item=e.target.closest(".ssa-palette-item");if(item)location.href=item.dataset.url});input.addEventListener("input",()=>{active=0;render()});input.addEventListener("keydown",e=>{const count=list.querySelectorAll(".ssa-palette-item").length;if(e.key==="ArrowDown"){e.preventDefault();active=Math.min(active+1,count-1);render()}else if(e.key==="ArrowUp"){e.preventDefault();active=Math.max(active-1,0);render()}else if(e.key==="Enter"){e.preventDefault();list.querySelectorAll(".ssa-palette-item")[active]?.click()}else if(e.key==="Escape")close()});document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();wrap.classList.contains("open")?close():open()}else if(e.key==="Escape")close()});render()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
