import { auth, db } from "../js/firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { collection, doc, getDocs, onSnapshot, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const $ = id => document.getElementById(id);
const coursesRef = collection(db, "courses");
let courses = [], filteredCourses = [], instructors = [];
const number = v => Number(v) || 0;
const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const dateValue = v => v?.toDate ? v.toDate().getTime() : new Date(v || 0).getTime();
const formatDate = v => { const d = v?.toDate ? v.toDate() : new Date(v || 0); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}); };
const money = v => number(v).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0});
const titleCase = v => String(v || "").replace(/(^|[-_\s])([a-z])/g, (_,p,c)=>`${p}${c.toUpperCase()}`);
const initials = n => String(n || "?").trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join("") || "?";
const notify = (m,t="success") => window.showFounderToast ? window.showFounderToast(m,t) : window.ssaToast?.(m,t);

function currentTutor(course){ return course.tutorName || instructors.find(i=>i.id===course.instructorId)?.name || "Unassigned"; }
function applyFilters(){ const search=($('courseSearch')?.value||'').trim().toLowerCase(); const status=$('statusFilter')?.value||'all',category=$('categoryFilter')?.value||'all',tutor=$('tutorFilter')?.value||'all',level=$('levelFilter')?.value||'all',sort=$('sortCourses')?.value||'latest'; filteredCourses=courses.filter(c=>{const hay=[c.title,c.description,c.category,currentTutor(c)].join(' ').toLowerCase();return(!search||hay.includes(search))&&(status==='all'||String(c.status||'draft').toLowerCase()===status)&&(category==='all'||c.category===category)&&(tutor==='all'||String(c.instructorId||'')===tutor)&&(level==='all'||String(c.level||'')===level)}); filteredCourses.sort((a,b)=>sort==='popular'?number(b.totalStudents)-number(a.totalStudents):sort==='rating'?number(b.rating)-number(a.rating):sort==='alphabetical'?String(a.title||'').localeCompare(String(b.title||'')):dateValue(b.createdAt||b.created_at)-dateValue(a.createdAt||a.created_at)); renderCourses(); }
function renderCourses(){const grid=$('coursesGrid'),empty=$('emptyState');if(!grid)return;grid.innerHTML=`<div class="courses-table-wrap"><table class="courses-table"><thead><tr><th>Course</th><th>Category</th><th>Instructor</th><th>Level</th><th>Students</th><th>Lessons</th><th>Revenue</th><th>Rating</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>${filteredCourses.map(courseRow).join('')}</tbody></table></div>`;if(empty)empty.hidden=filteredCourses.length!==0;if(!filteredCourses.length)grid.innerHTML='';grid.style.display=filteredCourses.length?'block':'none';refreshIcons();}
function courseRow(c){const status=String(c.status||'draft').toLowerCase(),tutor=currentTutor(c),next=status==='published'?'draft':'published';return `<tr><td><div class="course-name-cell"><span class="course-initial">${esc(initials(c.title))}</span><div><strong>${esc(c.title||'Untitled Course')}</strong><small>${esc((c.description||'No description').slice(0,70))}</small></div></div></td><td>${esc(c.category||'—')}</td><td>${esc(tutor)}</td><td>${esc(c.level||'—')}</td><td>${number(c.totalStudents).toLocaleString()}</td><td>${number(c.lessonCount)}</td><td>${money(c.revenue)}</td><td>${number(c.rating)>0?`⭐ ${number(c.rating).toFixed(1)}`:'—'}</td><td><span class="course-status-text ${esc(status)}">${esc(titleCase(status))}</span></td><td>${esc(formatDate(c.updatedAt||c.updated_at||c.createdAt))}</td><td><div class="table-actions"><button class="action-btn" data-action="view" data-id="${esc(c.id)}" title="View"><i class="fas fa-eye"></i></button><button class="action-btn" data-action="status" data-id="${esc(c.id)}" data-status="${next}" title="${next==='published'?'Publish':'Unpublish'}"><i class="fas fa-power-off"></i></button><button class="action-btn" data-action="feature" data-id="${esc(c.id)}" title="Feature"><i class="fas fa-star"></i></button><button class="action-btn danger" data-action="archive" data-id="${esc(c.id)}" title="Archive"><i class="fas fa-box-archive"></i></button></div></td></tr>`;}
function populateFilters(){const category=$('categoryFilter'),tutor=$('tutorFilter');if(!category||!tutor)return;const oldC=category.value,oldT=tutor.value;category.innerHTML=`<option value="all">All Categories</option>`+[...new Set(courses.map(c=>c.category).filter(Boolean))].sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');tutor.innerHTML=`<option value="all">All Tutors</option>`+instructors.map(i=>`<option value="${esc(i.id)}">${esc(i.name||i.email||'Instructor')}</option>`).join('');category.value=[...category.options].some(o=>o.value===oldC)?oldC:'all';tutor.value=[...tutor.options].some(o=>o.value===oldT)?oldT:'all';}
function renderDataSummary(){const summary=$('courseDataSummary');if(!summary)return;const published=courses.filter(c=>String(c.status||'draft').toLowerCase()==='published').length,drafts=courses.filter(c=>String(c.status||'draft').toLowerCase()==='draft').length;summary.textContent=`${courses.length} courses loaded from Firestore · ${published} published · ${drafts} drafts`;}
function openDrawer(id){const c=courses.find(x=>x.id===id);if(!c||!$('courseDrawer'))return;const status=String(c.status||'draft').toLowerCase();$('drawerContent').innerHTML=`<div class="drawer-profile"><div class="drawer-course-icon">${esc(initials(c.title))}</div><span class="course-status-text ${esc(status)}">${esc(titleCase(status))}</span><h2 class="drawer-title">${esc(c.title||'Untitled Course')}</h2><p class="drawer-description">${esc(c.description||'No description available.')}</p><div class="drawer-meta"><div class="meta-card"><span>Category</span><strong>${esc(c.category||'—')}</strong></div><div class="meta-card"><span>Level</span><strong>${esc(c.level||'—')}</strong></div><div class="meta-card"><span>Students</span><strong>${number(c.totalStudents).toLocaleString()}</strong></div><div class="meta-card"><span>Lessons</span><strong>${number(c.lessonCount)}</strong></div><div class="meta-card"><span>Rating</span><strong>${number(c.rating)>0?`⭐ ${number(c.rating).toFixed(1)}`:'—'}</strong></div><div class="meta-card"><span>Revenue</span><strong>${money(c.revenue)}</strong></div></div><div class="drawer-tutor"><div class="tutor-avatar">${esc(initials(currentTutor(c)))}</div><div><h4>${esc(currentTutor(c))}</h4><p>Assigned instructor</p></div></div><label class="drawer-instructor-control"><span>Assigned instructor</span><select id="courseInstructorSelect"><option value="">Unassigned</option>${instructors.map(i=>`<option value="${esc(i.id)}" ${c.instructorId===i.id?'selected':''}>${esc(i.name||i.email||'Instructor')}</option>`).join('')}</select></label><div class="drawer-actions"><button class="secondary-btn" data-drawer-action="assign" data-id="${esc(c.id)}">Save Instructor</button><button class="secondary-btn" data-drawer-action="status" data-id="${esc(c.id)}" data-status="${status==='published'?'draft':'published'}">${status==='published'?'Unpublish':'Publish'}</button><button class="primary-btn" data-drawer-action="feature" data-id="${esc(c.id)}">${c.featured?'Unfeature':'Feature'}</button><button class="warning-btn" data-drawer-action="archive" data-id="${esc(c.id)}">Archive</button></div></div>`;$('courseDrawer').classList.add('open');$('courseDrawer').setAttribute('aria-hidden','false');$('drawerBackdrop')?.classList.add('open');refreshIcons();}
function closeDrawer(){$('courseDrawer')?.classList.remove('open');$('courseDrawer')?.setAttribute('aria-hidden','true');$('drawerBackdrop')?.classList.remove('open');}
async function updateCourse(id,data,message){try{await updateDoc(doc(db,'courses',id),{...data,updatedAt:serverTimestamp()});notify(message);}catch(e){console.error(e);notify(e.message||'Unable to update course.','error');}}
async function toggleFeature(id){const c=courses.find(x=>x.id===id);if(c)await updateCourse(id,{featured:!c.featured},c.featured?'Course unfeatured.':'Course featured.');}
async function setStatus(id,status){await updateCourse(id,{status},`Course ${status==='published'?'published':'unpublished'}.`);closeDrawer();}
async function archive(id){const c=courses.find(x=>x.id===id);if(!c)return;const confirmed=await window.ssaConfirm?.(`Archive “${c.title||'this course'}”? It will no longer appear as an active course.`,{title:'Archive course',confirmText:'Archive',cancelText:'Keep course',tone:'danger',icon:'📦'});if(!confirmed)return;await updateCourse(id,{status:'archived'},'Course archived.');closeDrawer();}
async function assignInstructor(id){const select=$('courseInstructorSelect');if(!select)return;const i=instructors.find(x=>x.id===select.value);await updateCourse(id,{instructorId:i?.id||null,tutorName:i?.name||i?.email||'Unassigned'},'Instructor assignment saved.');closeDrawer();}
function exportCSV(){if(!courses.length){notify('No courses to export.','error');return;}const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const rows=[["Title","Category","Tutor","Level","Students","Lessons","Revenue","Rating","Status","Featured"],...courses.map(c=>[c.title,c.category,currentTutor(c),c.level,number(c.totalStudents),number(c.lessonCount),number(c.revenue),number(c.rating).toFixed(1),c.status,c.featured?'Yes':'No'])].map(r=>r.map(q).join(','));const blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ssa-courses-report.csv';a.click();URL.revokeObjectURL(url);}
function refreshIcons(){window.lucide?.createIcons?.();}
function bindEvents(){['courseSearch','statusFilter','categoryFilter','tutorFilter','levelFilter','sortCourses'].forEach(id=>$(id)?.addEventListener(id==='courseSearch'?'input':'change',applyFilters));$('exportCourses')?.addEventListener('click',exportCSV);$('closeDrawer')?.addEventListener('click',closeDrawer);$('drawerBackdrop')?.addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();});document.addEventListener('click',async e=>{const action=e.target.closest('[data-action]');if(action){const id=action.dataset.id;if(action.dataset.action==='view')openDrawer(id);else if(action.dataset.action==='feature')await toggleFeature(id);else if(action.dataset.action==='status')await setStatus(id,action.dataset.status);else if(action.dataset.action==='archive')await archive(id);return;}const drawerAction=e.target.closest('[data-drawer-action]');if(drawerAction){const id=drawerAction.dataset.id;if(drawerAction.dataset.drawerAction==='assign')await assignInstructor(id);else if(drawerAction.dataset.drawerAction==='feature')await toggleFeature(id);else if(drawerAction.dataset.drawerAction==='status')await setStatus(id,drawerAction.dataset.drawerAction==='status'&&drawerAction.dataset.status);else if(drawerAction.dataset.drawerAction==='archive')await archive(id);}});}
async function loadInstructors(){try{const snap=await getDocs(collection(db,'instructors'));instructors=snap.docs.map(d=>({id:d.id,...d.data()})).filter(i=>String(i.status||'').toLowerCase()!=='suspended');}catch(e){console.error(e);instructors=[];}}
function subscribeCourses(){onSnapshot(coursesRef,snap=>{courses=snap.docs.map(d=>({id:d.id,...d.data()}));populateFilters();renderDataSummary();applyFilters();$('loadingGrid')&&($('loadingGrid').style.display='none');},e=>{console.error(e);$('loadingGrid')&&($('loadingGrid').style.display='none');notify('Unable to load courses from Firestore.','error');});}
onAuthStateChanged(auth,async user=>{if(!user){location.href='../login.html';return;}bindEvents();await loadInstructors();subscribeCourses();});
