import { db } from "../js/firebase.js";
import { collection,onSnapshot,addDoc,doc,updateDoc,serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const $=id=>document.getElementById(id); const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
let students=[],editingId=null,page=1;const size=10;let stop=null;
const time=v=>v?.toMillis?v.toMillis():v?.toDate?v.toDate().getTime():new Date(v||0).getTime()||0;
const date=v=>time(v)?new Date(time(v)).toLocaleDateString():"—";
const toast=(m,t="success")=>window.showFounderToast?.(m,t)||window.showToast?.(m,t);
function stats(){const active=students.filter(s=>String(s.status||"").toLowerCase()==="active").length;const suspended=students.filter(s=>String(s.status||"").toLowerCase()==="suspended").length;const grad=students.filter(s=>String(s.status||"").toLowerCase()==="graduated").length;const now=new Date();const fresh=students.filter(s=>{const d=new Date(time(s.createdAt));return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();}).length;const progress=students.reduce((n,s)=>n+Math.max(0,Math.min(100,Number(s.progress??s.stats?.progress)||0)),0);$("studentCount")&&( $("studentCount").textContent=students.length);$("activeStudentCount")&&($("activeStudentCount").textContent=active);$("suspendedCount")&&($("suspendedCount").textContent=suspended);$("graduatedCount")&&($("graduatedCount").textContent=grad);$("newStudentCount")&&($("newStudentCount").textContent=fresh);$("completionRate")&&($("completionRate").textContent=students.length?`${Math.round(progress/students.length)}%`:"0%");$("studentTotal")&&($("studentTotal").textContent=`${students.length} ${students.length===1?"Student":"Students"}`);}
function filtered(){const q=String($("studentSearch")?.value||"").toLowerCase().trim(),course=String($("courseFilter")?.value||"").toLowerCase(),status=String($("statusFilter")?.value||"").toLowerCase();const out=students.filter(s=>{const name=String(s.name||s.fullName||"").toLowerCase(),email=String(s.email||"").toLowerCase(),ad=String(s.admissionNumber||"").toLowerCase(),co=String(s.courseName||s.course||"").toLowerCase(),st=String(s.status||"pending").toLowerCase();return(!q||name.includes(q)||email.includes(q)||ad.includes(q))&&(!course||co===course)&&(!status||st===status);});const sort=$("sortStudents")?.value||"newest";out.sort((a,b)=>sort==="name"?String(a.name||a.fullName||"").localeCompare(String(b.name||b.fullName||"")):sort==="oldest"?time(a.createdAt)-time(b.createdAt):time(b.createdAt)-time(a.createdAt));return out;}
function render(){const body=$("studentsTableBody");if(!body)return;const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,pages);const slice=rows.slice((page-1)*size,page*size);if(!slice.length){body.innerHTML='<tr><td colspan="8" class="empty-state"><div class="empty-content"><div class="empty-icon">🎓</div><h3>No Students Found</h3><p>Students will appear here after registration.</p></div></td></tr>';}else body.innerHTML=slice.map(s=>{const name=esc(s.name||s.fullName||"Unnamed Student"),status=String(s.status||"Pending"),p=Math.max(0,Math.min(100,Number(s.progress??s.stats?.progress)||0));return `<tr><td><div class="student-info"><div class="student-avatar">${esc(name.charAt(0).toUpperCase())}</div><div class="student-details"><strong>${name}</strong><small>${esc(s.admissionNumber||"Pending")}</small></div></div></td><td>${esc(s.courseName||s.course||"Not Assigned")}</td><td>${esc(s.email||"—")}</td><td>${esc(s.phone||"—")}</td><td><span class="status status-badge ${esc(status.toLowerCase())}">${esc(status)}</span></td><td><div class="progress"><div class="progress-bar"><div class="progress-fill" style="width:${p}%"></div></div><span>${p}%</span></div></td><td>${date(s.createdAt)}</td><td><div class="action-buttons"><button class="action-btn view" data-action="edit" data-id="${esc(s.id)}" title="Edit"><i data-lucide="eye"></i></button><button class="action-btn" data-action="toggle" data-id="${esc(s.id)}" title="Suspend/restore"><i data-lucide="${status.toLowerCase()==="suspended"?"play":"pause"}"></i></button></div></td></tr>`;}).join("");$("pageInfo")&&($("pageInfo").textContent=`Page ${page} of ${pages}`);$("prevPage")&&($("prevPage").disabled=page<=1);$("nextPage")&&($("nextPage").disabled=page>=pages);window.lucide?.createIcons();}
function populateCourses(){const select=$("courseFilter");if(!select)return;const current=select.value;const values=[...new Set(students.map(s=>s.courseName||s.course).filter(Boolean))].sort();select.innerHTML='<option value="">All Courses</option>'+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("");if(values.includes(current))select.value=current;}
function subscribe(){stop?.();const body=$("studentsTableBody");if(body)body.innerHTML='<tr><td colspan="8" class="empty-state"><div class="empty-content"><div class="empty-icon">✦</div><h3>Syncing student records</h3><p>Connecting to the academy database…</p></div></td></tr>';stop=onSnapshot(collection(db,"students"),snap=>{students=snap.docs.map(d=>({id:d.id,...d.data()}));stats();populateCourses();page=1;render();},err=>{console.error(err);toast("Student records could not be loaded. Check Firestore rules.","error");});}
function open(student){const modal=$("studentModal"),form=$("studentForm");if(!modal||!form)return;editingId=student?.id||null;form.reset();$("studentName").value=student?.name||student?.fullName||"";$("studentEmail").value=student?.email||"";$("studentPhone").value=student?.phone||"";$("studentCourse").value=student?.courseName||student?.course||"";$("studentStatus").value=String(student?.status||"active").toLowerCase();modal.classList.add("active");document.body.classList.add("modal-open");$("studentName")?.focus();}
function close(){ $("studentModal")?.classList.remove("active");document.body.classList.remove("modal-open");editingId=null;}
$("addStudentBtn")?.addEventListener("click",()=>open());$("closeStudentModal")?.addEventListener("click",close);$("studentModal")?.addEventListener("click",e=>{if(e.target===$("studentModal"))close();});
$("studentForm")?.addEventListener("submit",async e=>{e.preventDefault();const name=$("studentName")?.value.trim(),email=$("studentEmail")?.value.trim(),phone=$("studentPhone")?.value.trim(),course=$("studentCourse")?.value.trim(),status=$("studentStatus")?.value||"active";if(!name||!email||!course)return toast("Complete the required student fields.","warning");try{const record={name,email,phone,courseName:course,course,status:status.charAt(0).toUpperCase()+status.slice(1),updatedAt:serverTimestamp()};if(editingId)await updateDoc(doc(db,"students",editingId),record);else await addDoc(collection(db,"students"),{...record,role:"student",admissionNumber:`SSA-${new Date().getFullYear()}-${String(students.length+1).padStart(4,"0")}`,progress:0,createdAt:serverTimestamp()});close();toast(editingId?"Student updated successfully.":"Student added successfully.");}catch(err){console.error(err);toast(err.message||"Unable to save student.","error");}});
$("studentsTableBody")?.addEventListener("click",async e=>{const b=e.target.closest("button[data-id]");if(!b)return;const s=students.find(x=>x.id===b.dataset.id);if(!s)return;if(b.dataset.action==="edit")return open(s);const next=String(s.status||"").toLowerCase()==="suspended"?"Active":"Suspended";const ok=await window.ssaConfirm?.(`${next==="Suspended"?"Suspend":"Restore"} ${s.name||s.fullName||"this student"}?`,{title:next==="Suspended"?"Suspend student":"Restore student",confirmText:next==="Suspended"?"Suspend":"Restore",tone:next==="Suspended"?"danger":"info"});if(!ok)return;try{await updateDoc(doc(db,"students",s.id),{status:next,updatedAt:serverTimestamp()});toast(`Student ${next.toLowerCase()}.`);}catch(err){toast(err.message||"Unable to update student.","error");}});
["studentSearch","courseFilter","statusFilter","sortStudents"].forEach(id=>$(id)?.addEventListener("input",()=>{page=1;render()}));$("courseFilter")?.addEventListener("change",()=>{page=1;render()});$("statusFilter")?.addEventListener("change",()=>{page=1;render()});$("sortStudents")?.addEventListener("change",()=>{page=1;render()});$("refreshStudents")?.addEventListener("click",subscribe);$("prevPage")?.addEventListener("click",()=>{if(page>1){page--;render()}});$("nextPage")?.addEventListener("click",()=>{if(page<Math.ceil(filtered().length/size)){page++;render()}});
$("exportStudentsBtn")?.addEventListener("click",()=>{const rows=[["Name","Email","Phone","Course","Status","Admission Number"],...filtered().map(s=>[s.name||s.fullName||"",s.email||"",s.phone||"",s.courseName||s.course||"",s.status||"",s.admissionNumber||""])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="spark-stack-students.csv";a.click();});
window.addEventListener("beforeunload",()=>stop?.());subscribe();
