import { auth, db } from "../../../js/firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { collection, doc, getDoc, addDoc, onSnapshot, orderBy, query, serverTimestamp, updateDoc, limit } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const params=new URLSearchParams(location.search),chatId=params.get("chatId")||params.get("conversation");
const box=document.getElementById("chatMessages"),input=document.getElementById("messageInput"),sendBtn=document.getElementById("sendBtn"),nameEl=document.getElementById("chatName"),statusEl=document.getElementById("chatStatus"),avatar=document.getElementById("chatAvatar");
let user=null,profile=null,unsubscribe=null;
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
function renderMessage(item){const data=item.data(),mine=data.senderId===user.uid,node=document.createElement("div");node.className=mine?"message sent":"message received";const stamp=data.createdAt?.toDate?.()?data.createdAt.toDate():new Date();node.innerHTML=`<div class="message-text">${esc(data.text||data.body||"")}</div><div class="message-meta"><time>${stamp.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time>${mine?"<span class=\"message-read\">✓</span>":""}</div>`;box.appendChild(node);}
async function boot(){if(!chatId){location.href="messages.html";return;}const chatSnap=await getDoc(doc(db,"chats",chatId));if(!chatSnap.exists())throw new Error("Conversation not found.");const chat=chatSnap.data();if(!(chat.participants||[]).includes(user.uid))throw new Error("You are not a participant in this conversation.");const peer=(chat.members||[]).find(m=>m.uid!==user.uid)||{};nameEl.textContent=peer.name||peer.email||"Conversation";statusEl.textContent="Messaging";if(peer.photo)avatar.src=peer.photo;box.innerHTML="";let q;try{q=query(collection(db,"chats",chatId,"messages"),orderBy("createdAt","asc"),limit(100));}catch(e){q=collection(db,"chats",chatId,"messages");}unsubscribe=onSnapshot(q,snap=>{box.innerHTML="";snap.docs.forEach(renderMessage);box.scrollTop=box.scrollHeight;},error=>console.error("Chat stream failed:",error));}
async function send(){const text=input?.value.trim();if(!text||!chatId||!user)return;sendBtn.disabled=true;try{await addDoc(collection(db,"chats",chatId,"messages"),{senderId:user.uid,text,createdAt:serverTimestamp()});await updateDoc(doc(db,"chats",chatId),{lastMessage:text,lastSenderId:user.uid,updatedAt:serverTimestamp()});input.value="";input.style.height="auto";input.focus();}catch(e){console.error(e);window.showToast?.("We couldn't send that message.","error");}finally{sendBtn.disabled=false;}}
sendBtn?.addEventListener("click",send);input?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}});document.getElementById("backBtn")?.addEventListener("click",()=>location.href="messages.html");
onAuthStateChanged(auth,async current=>{if(!current){location.href="../login.html";return;}user=current;const p=await getDoc(doc(db,"users",user.uid));profile=p.exists()?p.data():{};try{await boot();}catch(e){console.error("Chat load failed:",e);box.innerHTML=`<div class="empty-state"><h2>Conversation unavailable</h2><p>${esc(e.message)}</p></div>`;}});
window.addEventListener("beforeunload",()=>unsubscribe?.());
